---
title: "Variation in movement characteristics"
author: "Benjamin Michael Marshall"
date: '2022-04-11'
output:
  bookdown::html_document2:
    theme: yeti
    highlight: monochrome
    # css: system.file("extdata", "style.css", package = "abmAnimalMovement")
    css: styleOverwrite.css
    fig_caption: true
vignette: |
  %\VignetteIndexEntry{walkthrough} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
link-citations: yes
linkcolor: blue
bibliography: abmAnimalMovement_refs.bib
biblio-style: peerj
---
Text text text.

```{r setConstants, include = FALSE}
library(abmAnimalMovement)

set.seed(2022)
# landscape
landcapeLayersList <- genLandscape_quickTriple(2000, 2000, seed = 1)
# behaviour
b0 <- c(0.98, 0.001, 0.00001) # rest
b1 <- c(0.0005, 0.99, 0.02) # explore/move
b2 <- c(0.0005, 0.02, 0.97) # forage
behaveMatTest <- rbind(b0, b1, b2)
# shelter
shelterLocs <- data.frame(
  "x" = c(1020, 1050, 1050, 1010, 1035),
  "y" = c(1020, 1050, 1050, 1010, 1045)
)
shelterSize <- 1
# avoid
avoid <- data.frame(
  "x" = c(950, 1010, 990),
  "y" = c(950, 1090, 1050)
)
avoidTransformation <- 2
avoidModifier <- 4
# destination
destinationRange <- c(50, 2)
destinationDirection <- c(0, 0.01)
destinationTransformation <- 2
destinationModifier <- 2
# rest cycle
restData <- c(0.65, 0, 24, 24)
# additional cycles
c0 <- c(0.2, 0, 24, 24*4) # digest
c1 <- c(0.15, 0, 24, 24*28) # seasonal
cycleMat <- rbind(c0, c1)
# timesteps and options
start <- c(1000,1000)
simSteps <- 24*60 *14
des_options <- 10
options <- 12

mu_angle <- c(0, 0, 0)
k_angle <- c(0.6, 0.99, 0.6)
```

# Varying step lengths

```{r runVariations}

k_step_all = data.frame(
  "rest" = seq(1, 4, length.out = 3),
  "explore" = seq(2, 5, length.out = 3),
  "forage" = seq(2, 4, length.out = 3)
)
s_step_all = data.frame(
  "rest" = seq(0.5, 4, length.out = 3),
  "explore" = seq(1, 4, length.out = 3),
  "forage" = seq(1, 4, length.out = 3)
)

plotNumber <- dim(k_step_all)[1] * dim(s_step_all)[1]

listIndex <- 0
all_simRes <- vector("list", length = plotNumber)
for(i in 1:dim(k_step_all)[1]){
  
  for(j in 1:dim(s_step_all)[1]){
    listIndex <- listIndex + 1
    
     simRes <- abm_simulate(start = start,
                    timesteps = simSteps,
                    des_options = des_options,
                    options = options,
                    k_step = c(k_step_all[i,1],
                               k_step_all[i,2],
                               k_step_all[i,3]),
                    s_step = c(s_step_all[j,1],
                               s_step_all[j,2],
                               s_step_all[j,3]),
                    mu_angle = mu_angle,
                    k_angle = k_angle,
                    
                    shelterLocations = shelterLocs,
                    shelterSize = 1,
                    avoidPoints = avoid,
                    
                    destinationRange = c(50, 2),
                    destinationDirection = c(0, 0.01),
                    destinationTransformation = 2,
                    destinationModifier = 2,
                    avoidTransformation = 2,
                    avoidModifier = 4,
                    
                    behave_Tmat = behaveMatTest,
                    
                    rest_Cycle = restData,
                    additional_Cycles = cycleMat,
                    
                    shelteringMatrix = landcapeLayersList$memShelter,
                    foragingMatrix = landcapeLayersList$forage,
                    movementMatrix = landcapeLayersList$shelter)
    
    all_simRes[[listIndex]] <- simRes
    
  } # j
} # i

```

```{r plotVariations, fig.align='center', fig.width=11, fig.height=11, fig.cap="Varitaion of step length distribution."}

locationExtents <- do.call(rbind, lapply(all_simRes, function(x){
  data.frame("minx" = min(x$locations$x),
             "maxx" = max(x$locations$x),
             "miny" = min(x$locations$y),
             "maxy" = max(x$locations$y))
}))

listIndex <- 0
plotList <- vector("list", length = plotNumber)
for(i in 1:dim(k_step_all)[1]){
  
  for(j in 1:dim(s_step_all)[1]){
    listIndex <- listIndex + 1
    
    tempPlot <- abmMapPlot(all_simRes[[listIndex]],
                           shelterLocations = shelterLocs, avoidance = avoid,
                           timeLimits = c(1, simSteps)) +
      ggplot2::labs(title = 
                      paste0(paste0("k<sub>", c(0,1,2), "</sub>=",
                                    all_simRes[[listIndex]]$inputs$in_k_step),
                             paste0(", s<sub>", c(0,1,2), "</sub>=",
                                    all_simRes[[listIndex]]$inputs$in_s_step),
                             collapse = "; ")
      ) +
      ggplot2::theme(legend.position = "none",
                     plot.title = ggtext::element_markdown(size = 8),
                     # plot.title = ggplot2::element_text(size = 8),
                     axis.title.x = ggplot2::element_blank(),
                     axis.title.y = ggplot2::element_blank()) +
      ggplot2::coord_fixed(xlim = c(
        min(locationExtents$minx),
        max(locationExtents$maxx)
      ),
      ylim = c(
        min(locationExtents$miny),
        max(locationExtents$maxy)
      ))
    
    if(!j == 1){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.y = ggplot2::element_blank())
    }
    if(!i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.x = ggplot2::element_blank())
    }
    if(j == 1 & i == 2){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.y = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    if(j == 2 & i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.x = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    
    plotList[[listIndex]] <- tempPlot
    
  } # j
} # i

do.call(patchwork::wrap_plots, c(plotList, ncol = dim(k_step_all)[1]))

```

