---
title: "Variation in cycling parameters"
author: "Benjamin Michael Marshall"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    theme: yeti
    highlight: monochrome
    # css: system.file("extdata", "style.css", package = "abmAnimalMovement")
    css: styleOverwrite.css
    fig_caption: true
vignette: |
  %\VignetteIndexEntry{Variation_in_destination_parameters} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
link-citations: yes
linkcolor: blue
bibliography: abmAnimalMovement_refs.bib
biblio-style: peerj
---

Here we show the impact of changing some of the variables connected to the foraging destinations, and more generally how strong forces of attraction/avoidance are.

```{r setConstants, include=FALSE, echo=FALSE, message=FALSE}
library(abmAnimalMovement)

set.seed(2022)
# landscape
landcapeLayersList <- genLandscape_quickTriple(2000, 2000, seed = 1)
# behaviour
b0 <- c(0.98, 0.001, 0.00001) # rest
b1 <- c(0.0005, 0.99, 0.02) # explore/move
b2 <- c(0.0005, 0.02, 0.97) # forage
behaveMatTest <- rbind(b0, b1, b2)
# shelter
shelterLocs <- data.frame(
  "x" = c(1020, 1050, 1050, 1010, 1035),
  "y" = c(1020, 1050, 1050, 1010, 1045)
)
shelterSize <- 1
# avoid
avoid <- data.frame(
  "x" = c(950, 1010, 990),
  "y" = c(950, 1090, 1050)
)
avoidTransformation <- 2
avoidModifier <- 4
# destination
destinationRange <- c(50, 2)
destinationDirection <- c(0, 0.01)
destinationTransformation <- 2
destinationModifier <- 2
# rest cycle
restData <- c(0.65, 0, 24, 24)
# additional cycles
# c0 <- c(0.2, 0, 24, 24*4) # digest
c1 <- c(0.15, 0, 24, 24*28) # seasonal
# cycleMat <- rbind(c0, c1)
cycleMat <- rbind(c1)
# timesteps and options
start <- c(1000,1000)
simSteps <- 24*60 *5
des_options <- 10
options <- 12

k_step <- c(1, 3, 2)
s_step <- c(0.5, 1, 1)
mu_angle <- c(0, 0, 0)
k_angle <- c(0.6, 0.99, 0.6)
```

# Varying resting cycles

```{r runRestCycleVariations, include=FALSE, echo=FALSE, message=FALSE}

restData_Amp_all = seq(0.1, 0.9, length.out = 3)
restData_Tau_all = seq(12, 72, length.out = 3)

plotNumber <- length(restData_Amp_all)[1] * length(restData_Tau_all)[1]

listIndex <- 0
all_simRes <- vector("list", length = plotNumber)
for(i in 1:length(restData_Amp_all)[1]){
  
  for(j in 1:length(restData_Tau_all)[1]){
    listIndex <- listIndex + 1
    
    simRes <- abm_simulate(start = start,
                           timesteps = simSteps,
                           des_options = des_options,
                           options = options,
                           k_step = k_step,
                           s_step = s_step,
                           mu_angle = mu_angle,
                           k_angle = k_angle,
                           
                           shelterLocations = shelterLocs,
                           shelterSize = 1,
                           avoidPoints = avoid,
                           
                           destinationRange = destinationRange,
                           destinationDirection = destinationDirection,
                           destinationTransformation = 2,
                           destinationModifier = 2,
                           avoidTransformation = 2,
                           avoidModifier = 4,
                           
                           behave_Tmat = behaveMatTest,
                           
                           rest_Cycle = c(restData_Amp_all[i],
                                          -0.1,
                                          restData_Tau_all[j]/2,
                                          restData_Tau_all[j]),
                           additional_Cycles = cycleMat,
                           
                           shelteringMatrix = landcapeLayersList$memShelter,
                           foragingMatrix = landcapeLayersList$forage,
                           movementMatrix = landcapeLayersList$shelter)
    
    all_simRes[[listIndex]] <- simRes
    
  } # j
} # i

```

```{r plotRestCycleVariations, include=TRUE, echo=FALSE, message=FALSE, fig.align='center', fig.width=22, fig.height=11, fig.cap="Varitaion of ."}

locationExtents <- do.call(rbind, lapply(all_simRes, function(x){
  data.frame("minx" = min(x$locations$x),
             "maxx" = max(x$locations$x),
             "miny" = min(x$locations$y),
             "maxy" = max(x$locations$y))
}))

listIndex <- 0
plotList <- vector("list", length = plotNumber)
for(i in 1:length(restData_Amp_all)[1]){
  
  for(j in 1:length(restData_Tau_all)[1]){
    listIndex <- listIndex + 1
    
    tempPlot <- abmCyclePlot(all_simRes[[listIndex]],
                           timeLimits = c(1, simSteps)) +
    patchwork::plot_annotation(
      title = paste0("A=", all_simRes[[listIndex]]$inputs$in_rest_Cycle_A,
                     ", Tau=", all_simRes[[listIndex]]$inputs$in_rest_Cycle_TAU)
    )
    
    plotList[[listIndex]] <- tempPlot
    
  } # j
} # i

do.call(patchwork::wrap_plots, c(plotList, ncol = length(restData_Amp_all)[1]))

ggplot2::ggsave(here::here("inst/figures/plotRestCycleVariations.png"),
       width = 360, height = 180, units = "mm", dpi = 300)

```
