---
title: "Variation in destination parameters"
author: "Benjamin Michael Marshall"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    theme: yeti
    highlight: monochrome
    # css: system.file("extdata", "style.css", package = "abmAnimalMovement")
    css: styleOverwrite.css
    fig_caption: true
vignette: |
  %\VignetteIndexEntry{Variation_in_destination_parameters} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
link-citations: yes
linkcolor: blue
bibliography: abmAnimalMovement_refs.bib
biblio-style: peerj
---

Here we show the impact of changing some of the variables connected to the foraging destinations, and more generally how strong forces of attraction/avoidance are.

```{r setConstants, include=FALSE, echo=FALSE, message=FALSE}
library(abmAnimalMovement)

set.seed(2022)
# landscape
landcapeLayersList <- genLandscape_quickTriple(2000, 2000, seed = 1)
# behaviour
b0 <- c(0.98, 0.001, 0.00001) # rest
b1 <- c(0.0005, 0.99, 0.02) # explore/move
b2 <- c(0.0005, 0.02, 0.97) # forage
behaveMatTest <- rbind(b0, b1, b2)
# shelter
shelterLocs <- data.frame(
  "x" = c(1020, 1050, 1050, 1010, 1035),
  "y" = c(1020, 1050, 1050, 1010, 1045)
)
shelterSize <- 1
# avoid
avoid <- data.frame(
  "x" = c(950, 1010, 990),
  "y" = c(950, 1090, 1050)
)
avoidTransformation <- 2
avoidModifier <- 4
# destination
destinationRange <- c(50, 2)
destinationDirection <- c(0, 0.01)
destinationTransformation <- 2
destinationModifier <- 2
# rest cycle
restData <- c(0.65, 0, 24, 24)
# additional cycles
c0 <- c(0.2, 0, 24, 24*4) # digest
c1 <- c(0.15, 0, 24, 24*28) # seasonal
cycleMat <- rbind(c0, c1)
# timesteps and options
start <- c(1000,1000)
simSteps <- 24*60 *14
des_options <- 10
options <- 12

k_step <- c(1, 3, 2)
s_step <- c(0.5, 1, 1)
mu_angle <- c(0, 0, 0)
k_angle <- c(0.6, 0.99, 0.6)
```

# Varying distribution describing forgaing choices

```{r runDesRangeVariations, include=FALSE, echo=FALSE, message=FALSE}

destinationRange_all = seq(5, 100, length.out = 3)
destinationDirection_all = seq(0.1, 0.9, length.out = 3)

plotNumber <- length(destinationRange_all)[1] * length(destinationDirection_all)[1]

listIndex <- 0
all_simRes <- vector("list", length = plotNumber)
for(i in 1:length(destinationRange_all)[1]){
  
  for(j in 1:length(destinationDirection_all)[1]){
    listIndex <- listIndex + 1
    
    simRes <- abm_simulate(start = start,
                           timesteps = simSteps,
                           des_options = des_options,
                           options = options,
                           k_step = k_step,
                           s_step = s_step,
                           mu_angle = mu_angle,
                           k_angle = k_angle,
                           
                           shelterLocations = shelterLocs,
                           shelterSize = 1,
                           avoidPoints = avoid,
                           
                           destinationRange = c(destinationRange_all[i],
                                                destinationRange_all[i]/25),
                           destinationDirection = c(0, destinationDirection_all[j]),
                           destinationTransformation = 2,
                           destinationModifier = 2,
                           avoidTransformation = 2,
                           avoidModifier = 4,
                           
                           behave_Tmat = behaveMatTest,
                           
                           rest_Cycle = restData,
                           additional_Cycles = cycleMat,
                           
                           shelteringMatrix = landcapeLayersList$memShelter,
                           foragingMatrix = landcapeLayersList$forage,
                           movementMatrix = landcapeLayersList$shelter)
    
    all_simRes[[listIndex]] <- simRes
    
  } # j
} # i

```

```{r plotDesRangeVariations, include=TRUE, echo=FALSE, message=FALSE, fig.align='center', fig.width=11, fig.height=11, fig.cap="Varitaion of distance and angle distributions governing the location of foraging destinations."}

locationExtents <- do.call(rbind, lapply(all_simRes, function(x){
  data.frame("minx" = min(x$locations$x),
             "maxx" = max(x$locations$x),
             "miny" = min(x$locations$y),
             "maxy" = max(x$locations$y))
}))

listIndex <- 0
plotList <- vector("list", length = plotNumber)
for(i in 1:length(destinationRange_all)[1]){
  
  for(j in 1:length(destinationDirection_all)[1]){
    listIndex <- listIndex + 1
    
    tempPlot <- abmMapPlot(all_simRes[[listIndex]],
                           timeLimits = c(1, simSteps)) +
      ggplot2::labs(title =
                      paste0("k=", all_simRes[[listIndex]]$inputs$in_k_desRange, 
                             ", s=", all_simRes[[listIndex]]$inputs$in_s_desRange, 
                              "; kappa=", all_simRes[[listIndex]]$inputs$in_k_desDir)
      ) +
      ggplot2::theme(legend.position = "none",
                     plot.title = ggtext::element_markdown(size = 8),
                     # plot.title = ggplot2::element_text(size = 8),
                     axis.title.x = ggplot2::element_blank(),
                     axis.title.y = ggplot2::element_blank()) +
      ggplot2::coord_fixed(xlim = c(
        min(locationExtents$minx),
        max(locationExtents$maxx)
      ),
      ylim = c(
        min(locationExtents$miny),
        max(locationExtents$maxy)
      ))
    
    if(!j == 1){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.y = ggplot2::element_blank())
    }
    if(!i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.x = ggplot2::element_blank())
    }
    if(j == 1 & i == 2){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.y = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    if(j == 2 & i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.x = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    
    plotList[[listIndex]] <- tempPlot
    
  } # j
} # i

do.call(patchwork::wrap_plots, c(plotList, ncol = length(destinationRange_all)[1]))

ggplot2::ggsave(here::here("inst/figures/plotDesRangeVariations.png"),
       width = 180, height = 180, units = "mm", dpi = 300)

```

# Varying strengths/tranformations of attraction

```{r runDesAttracVariations, include=FALSE, echo=FALSE, message=FALSE}

destinationTransformation_all = seq(0, 2, length.out = 3)
destinationModifier_all = seq(0.1, 8, length.out = 3)

plotNumber <- length(destinationTransformation_all)[1] *
  length(destinationModifier_all)[1]

listIndex <- 0
all_simRes <- vector("list", length = plotNumber)
for(i in 1:length(destinationTransformation_all)[1]){
  
  for(j in 1:length(destinationModifier_all)[1]){
    listIndex <- listIndex + 1
    
    simRes <- abm_simulate(start = start,
                           timesteps = simSteps,
                           des_options = des_options,
                           options = options,
                           k_step = k_step,
                           s_step = s_step,
                           mu_angle = mu_angle,
                           k_angle = k_angle,
                           
                           shelterLocations = shelterLocs,
                           shelterSize = 1,
                           avoidPoints = avoid,
                           
                           destinationRange = destinationRange,
                           destinationDirection = destinationDirection,
                           destinationTransformation = destinationTransformation_all[i],
                           destinationModifier = destinationModifier_all[j],
                           avoidTransformation = 2,
                           avoidModifier = 4,
                           
                           behave_Tmat = behaveMatTest,
                           
                           rest_Cycle = restData,
                           additional_Cycles = cycleMat,
                           
                           shelteringMatrix = landcapeLayersList$memShelter,
                           foragingMatrix = landcapeLayersList$forage,
                           movementMatrix = landcapeLayersList$shelter)
    
    all_simRes[[listIndex]] <- simRes
    
  } # j
} # i

```

```{r plotDesAttracVariations, include=TRUE, echo=FALSE, message=FALSE, fig.align='center', fig.width=11, fig.height=11, fig.cap="Varitaion of strength of attraction to the location of destinations."}

locationExtents <- do.call(rbind, lapply(all_simRes, function(x){
  data.frame("minx" = min(x$locations$x),
             "maxx" = max(x$locations$x),
             "miny" = min(x$locations$y),
             "maxy" = max(x$locations$y))
}))

listIndex <- 0
plotList <- vector("list", length = plotNumber)
for(i in 1:length(destinationRange_all)[1]){
  
  for(j in 1:length(destinationDirection_all)[1]){
    listIndex <- listIndex + 1
    
    tempPlot <- abmMapPlot(all_simRes[[listIndex]],
                           timeLimits = c(1, simSteps)) +
      ggplot2::labs(title =
                      paste0("trans.=",
                             
                             ifelse(all_simRes[[listIndex]]$inputs$in_destinationTrans == 0,
                                    "no trans.",
                                  ifelse(all_simRes[[listIndex]]$inputs$in_destinationTrans == 1,
                                         "sqrt", "^2")), 
                             ", mod.=", all_simRes[[listIndex]]$inputs$in_destinationMod)
      ) +
      ggplot2::theme(legend.position = "none",
                     plot.title = ggtext::element_markdown(size = 8),
                     # plot.title = ggplot2::element_text(size = 8),
                     axis.title.x = ggplot2::element_blank(),
                     axis.title.y = ggplot2::element_blank()) +
      ggplot2::coord_fixed(xlim = c(
        min(locationExtents$minx),
        max(locationExtents$maxx)
      ),
      ylim = c(
        min(locationExtents$miny),
        max(locationExtents$maxy)
      ))
    
    if(!j == 1){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.y = ggplot2::element_blank())
    }
    if(!i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.x = ggplot2::element_blank())
    }
    if(j == 1 & i == 2){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.y = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    if(j == 2 & i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.x = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    
    plotList[[listIndex]] <- tempPlot
    
  } # j
} # i

do.call(patchwork::wrap_plots,
        c(plotList, ncol = length(destinationTransformation_all)[1]))

ggplot2::ggsave(here::here("inst/figures/plotDesAttracVariations.png"),
       width = 180, height = 180, units = "mm", dpi = 300)

```

# Varying strengths/tranformations of avoidance

```{r runAvoidVariations, include=FALSE, echo=FALSE, message=FALSE}

avoidTransformation_all = seq(0, 2, length.out = 3)
avoidModifier_all = seq(0.1, 8, length.out = 3)

plotNumber <- length(avoidTransformation_all)[1] *
  length(avoidModifier_all)[1]

listIndex <- 0
all_simRes <- vector("list", length = plotNumber)
for(i in 1:length(avoidTransformation_all)[1]){
  
  for(j in 1:length(avoidModifier_all)[1]){
    listIndex <- listIndex + 1
    
    simRes <- abm_simulate(start = start,
                           timesteps = simSteps,
                           des_options = des_options,
                           options = options,
                           k_step = k_step,
                           s_step = s_step,
                           mu_angle = mu_angle,
                           k_angle = k_angle,
                           
                           shelterLocations = shelterLocs,
                           shelterSize = 1,
                           avoidPoints = avoid,
                           
                           destinationRange = destinationRange,
                           destinationDirection = destinationDirection,
                           destinationTransformation = destinationTransformation,
                           destinationModifier = destinationModifier,
                           avoidTransformation = avoidTransformation_all[i],
                           avoidModifier = avoidModifier_all[j],
                           
                           behave_Tmat = behaveMatTest,
                           
                           rest_Cycle = restData,
                           additional_Cycles = cycleMat,
                           
                           shelteringMatrix = landcapeLayersList$memShelter,
                           foragingMatrix = landcapeLayersList$forage,
                           movementMatrix = landcapeLayersList$shelter)
    
    all_simRes[[listIndex]] <- simRes
    
  } # j
} # i

```

```{r plotAvoidVariations, include=TRUE, echo=FALSE, message=FALSE, fig.align='center', fig.width=11, fig.height=11, fig.cap="Varitaion of strength of attraction to the location of destinations."}

locationExtents <- do.call(rbind, lapply(all_simRes, function(x){
  data.frame("minx" = min(x$locations$x),
             "maxx" = max(x$locations$x),
             "miny" = min(x$locations$y),
             "maxy" = max(x$locations$y))
}))

listIndex <- 0
plotList <- vector("list", length = plotNumber)
for(i in 1:length(avoidTransformation_all)[1]){
  
  for(j in 1:length(avoidModifier_all)[1]){
    listIndex <- listIndex + 1
    
    tempPlot <- abmMapPlot(all_simRes[[listIndex]],
                           timeLimits = c(1, simSteps)) +
      ggplot2::labs(title =
                      paste0("trans.=",
                             
                             ifelse(all_simRes[[listIndex]]$inputs$in_avoidTrans == 0,
                                    "no trans.",
                                  ifelse(all_simRes[[listIndex]]$inputs$in_avoidTrans == 1,
                                         "sqrt", "^2")), 
                             ", mod.=", all_simRes[[listIndex]]$inputs$in_avoidMod)
      ) +
      ggplot2::theme(legend.position = "none",
                     plot.title = ggtext::element_markdown(size = 8),
                     # plot.title = ggplot2::element_text(size = 8),
                     axis.title.x = ggplot2::element_blank(),
                     axis.title.y = ggplot2::element_blank()) +
      ggplot2::coord_fixed(xlim = c(
        min(locationExtents$minx),
        max(locationExtents$maxx)
      ),
      ylim = c(
        min(locationExtents$miny),
        max(locationExtents$maxy)
      ))
    
    if(!j == 1){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.y = ggplot2::element_blank())
    }
    if(!i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.text.x = ggplot2::element_blank())
    }
    if(j == 1 & i == 2){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.y = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    if(j == 2 & i == 3){
      tempPlot <- tempPlot +
        ggplot2::theme(axis.title.x = ggplot2::element_text(hjust = 0.5,
                                                            vjust = 0.5))
    }
    
    plotList[[listIndex]] <- tempPlot
    
  } # j
} # i

do.call(patchwork::wrap_plots,
        c(plotList, ncol = length(avoidTransformation_all)[1]))

ggplot2::ggsave(here::here("inst/figures/plotAvoidVariations.png"),
       width = 180, height = 180, units = "mm", dpi = 300)

```
