---
title: "Setting up R package with Cpp"
author: "Benjamin Michael Marshall"
date: "03/11/2021"
output: html_document
---

Setting up a new project in a R package format (with Cpp additions)

Need 
install.packages("devtools")
install.packages("roxygen2")

Make git repo

Clone git repo to computer

Run usethis::create_package(getwd()) to genereate the r package files

Run roxygen2::roxygenise() to produce man folder for docuemtnation

Add
LinkingTo: Rcpp
Imports: Rcpp
To the DESRCIPTION file

Make sure your NAMESPACE includes:
useDynLib(mypackage)
importFrom(Rcpp, sourceCpp)
you can use usethis::use_rcpp() to achieve this
Rcpp::Rcpp.package.skeleton() will alo do some of this

Run 
dir.create("./src/")
to make location for Cpp files

use devtools::document() to generate exported function documentation


Rcpp::compileAttributes()
may be needed for making Cpp function available in R, but requires in // [[Rcpp::export]] in the function file

this builds a package level document that is needed to use Rcpp in package
usethis::use_package_doc()

This is needed in the R function so it can find the Cpp function
#' @useDynLib abmAnimalMovement


## For compiling with visualstudio and heavy installs
# not sure if needed because rcpp uses Rtools

https://sourceforge.net/projects/mingw/
https://techsupportwhale.com/install-gcc-compiler-on-windows/
