# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sample_test
#' @name sample_test
#' @param vect vector length
#' @return Matrix of locations chosen
NULL

sample_test <- function(vect) {
    .Call('_abmAnimalMovement_sample_test', PACKAGE = 'abmAnimalMovement', vect)
}

#' vonmises
#' https://statisticaloddsandends.wordpress.com/2020/02/25/what-is-the-von-mises-distribution/
#' https://gist.github.com/SiyuanQi/10ed29aa850e26e2e1251af04f5427ec
#' http://dirk.eddelbuettel.com/code/bh.html
#' https://garylarson.weebly.com/blog/category/rcpp
#' @name vonmises
#' @param N number to draw
#' @param kappa
#' @param mu
#' @return Vector pulled from vonmises
vonmises <- function(N, kappa, mu) {
    .Call('_abmAnimalMovement_vonmises', PACKAGE = 'abmAnimalMovement', N, kappa, mu)
}

#' Basic random walk
#' @name walk_options_xy
#' @param startx The x coord start location
#' @param starty The y coord start location
#' @param steps The number of steps to be simulated
#' @param options The number of options to be considered at each step
#' @param normmean Parameter describing step length
#' @param normsd Parameter describing step angle
#' @param meanang Parameter describing angle
#' @param sdang Parameter describing angle variation
#' @param envMat1 Environmental matrix 1
#' @return Matrix of locations chosen
NULL

walk_options_xy <- function(startx, starty, steps, options, normmean, normsd, meanang, sdang, envMat1) {
    .Call('_abmAnimalMovement_walk_options_xy', PACKAGE = 'abmAnimalMovement', startx, starty, steps, options, normmean, normsd, meanang, sdang, envMat1)
}

