# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find max
#' @name find_max
#' @param vect
#' @return index of max
NULL

find_max <- function(vect) {
    .Call('_abmAnimalMovement_find_max', PACKAGE = 'abmAnimalMovement', vect)
}

#' @title cpp_sample_options
#' @name cpp_sample_options
#' @description The C++ sample function that takes a vector of weights and
#'   randomly returns an integer of the choice. Sampling solution based on:
#' [link](https://stackoverflow.com/questions/57599509/c-random-non-repeated-integers-with-weights).
#' With the of definition of pow2 coming from: [link](https://stackoverflow.com/questions/101439/the-most-efficient-way-to-implement-an-integer-based-power-function-powint-int).
#' A solution for the setting the random seed from: [link](https://www.r-bloggers.com/2018/09/using-rs-set-seed-to-set-seeds-for-use-in-c-c-including-rcpp/).
#'
#' @param W A vector of weights.
#' @param SEED The seed to be used for the sampling.
#' @details Requires a new seed for each run as a separate seed is set
#'   internally every time the function runs.
#' @return An integer corresponding to the chosen weight in the initially
#'   provided vector. __NOTE: indexing begins at 0 matching C++ convention__.
NULL

cpp_sample_options <- function(W, SEED) {
    .Call('_abmAnimalMovement_cpp_sample_options', PACKAGE = 'abmAnimalMovement', W, SEED)
}

#' @name cpp_vonmises
#' @title cpp_vonmises
#' @description A C++ conversion of the *rvm* function provided by the [CircStats package](https://cran.r-project.org/web/packages/CircStats/index.html).
#' @param N of values to draw.
#' @param MU The mean of the distribution (\eqn{\mu}).
#' @param KAPPA The concentration of the distribution (\eqn{\kappa}).
#' @return A vector drawn from a von Mises distribution equal in length to N.
#'
#' @references
#' S-plus original by Ulric Lund and R port by Claudio Agostinelli (2018). CircStats: Circular Statistics, from Topics in Circular Statistics (2001). R package version 0.2-6. https://CRAN.R-project.org/package=CircStats
#'
cpp_vonmises <- function(N, MU, KAPPA) {
    .Call('_abmAnimalMovement_cpp_vonmises', PACKAGE = 'abmAnimalMovement', N, MU, KAPPA)
}

#' Basic random walk
#' @name walk_options_xy
#' @param startx The x coord start location
#' @param starty The y coord start location
#' @param steps The number of steps to be simulated
#' @param options The number of options to be considered at each step
#' @param normmean Parameter describing step length
#' @param normsd Parameter describing step angle
#' @param meanang Parameter describing angle
#' @param sdang Parameter describing angle variation
#' @param envMat1 Environmental matrix 1
#' @return Matrix of locations chosen
NULL

walk_options_xy <- function(startx, starty, steps, options, k_step, s_step, mu_angle, k_angle, envMat1, seeds) {
    .Call('_abmAnimalMovement_walk_options_xy', PACKAGE = 'abmAnimalMovement', startx, starty, steps, options, k_step, s_step, mu_angle, k_angle, envMat1, seeds)
}

