# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name cpp_abm_simulate
#' @title cpp_abm_simulate
#' @description The C++ function that runs the agent based animal movement
#'   model.
#' @param startx The x coordinate start location
#' @param starty The y coordinate start location
#' @param timesteps The number of timesteps to be simulated
#' @param ndes The number of possible destination considered for
#'   foraging.
#' @param nopt The number of options to be considered at each timestep
#' @param shelter_locs_x A vector of shelter locations x coordinates.
#' @param shelter_locs_y A vector of shelter locations y coordinates.
#' @param avoidPoints_x A vector of avoidance point x coordinates.
#' @param avoidPoints_y A vector of avoidance point y coordinates.
#' @param destinationTrans 0 - no transformation applied to the distance to
#'   destination weighting, 1 - distance to destination weighing is
#'   square-rooted, 2 - distance to destination weighting is squared
#' @param destinationMod A coefficient to be applied to the distance to
#'   destination weighting.
#' @param avoidTrans 0 - no transformation applied to the distance to avoidance
#'   points weighting, 1 - distance to avoidance points weighing is
#'   square-rooted, 2 - distance to avoidance points weighting is squared
#' @param avoidMod A coefficient to be applied to the avoidance points
#'   weighting.
#' @param k_step Parameter describing step length
#' @param s_step Parameter describing step
#' @param mu_angle Parameter describing angle
#' @param k_angle Parameter describing angle variation
#' @param b0_Options Behave transitional probs for behave 0
#' @param b1_Options Behave transitional probs for behave 1
#' @param b2_Options Behave transitional probs for behave 2
#' @param rest_Cycle_A The amplitude of the resting/active cycle.
#' @param rest_Cycle_M The cycle offset from 0 (Midline Statistic Of Rhythm) of
#'   the resting/active cycle.
#' @param rest_Cycle_PHI The offset of the cycle (\eqn{\phi}; i.e., acrophase)
#'   of the resting/active cycle.
#' @param rest_Cycle_TAU Cycle frequency (\eqn{\tau}; i.e., period) of the
#'   resting/active cycle.
#' @param addCycles A integer describing how many additional activity cycles to
#'   include, can be zero.
#' @param add_Cycle_A The amplitude of the additional active cycles, should be
#'   a vector of doubles.
#' @param add_Cycle_M The cycle offset from 0 (Midline Statistic Of Rhythm) of
#'   the additional active cycles, should be a vector of doubles.
#' @param add_Cycle_PHI The offset of the cycle (\eqn{\phi}; i.e., acrophase)
#'   of the additional active cycles, should be a vector of doubles.
#' @param add_Cycle_TAU Cycle frequency (\eqn{\tau}; i.e., period) of the
#'   additional active cycles, should be a vector of doubles.
#' @param shelterMatrix The matrix describing shelter site quality.
#' @param forageMatrix The matrix describing foraging site quality.
#' @param moveMatrix The matrix describing movement ease.
#' @param seeds A number of seeds the length of the number of timesteps, ideally
#'   generated by R handling function.
#' @return A list of simulated animal details to be passed and handled by R
#'   function to make easier to use.
#' @details Requires cmath and headers for smaller C++ functions for draws. #'
#'   @seealso [abm_simulate()] is the R function wrap with more in depth
#'   documentation.
NULL

cpp_abm_simulate <- function(startx, starty, timesteps, ndes, nopt, shelter_locs_x, shelter_locs_y, sSiteSize, avoidPoints_x, avoidPoints_y, k_desRange, s_desRange, mu_desDir, k_desDir, destinationTrans, destinationMod, avoidTrans, avoidMod, k_step, s_step, mu_angle, k_angle, rescale, b0_Options, b1_Options, b2_Options, rest_Cycle_A, rest_Cycle_M, rest_Cycle_PHI, rest_Cycle_TAU, addCycles, add_Cycle_A, add_Cycle_M, add_Cycle_PHI, add_Cycle_TAU, shelterMatrix, forageMatrix, moveMatrix, seeds) {
    .Call('_abmAnimalMovement_cpp_abm_simulate', PACKAGE = 'abmAnimalMovement', startx, starty, timesteps, ndes, nopt, shelter_locs_x, shelter_locs_y, sSiteSize, avoidPoints_x, avoidPoints_y, k_desRange, s_desRange, mu_desDir, k_desDir, destinationTrans, destinationMod, avoidTrans, avoidMod, k_step, s_step, mu_angle, k_angle, rescale, b0_Options, b1_Options, b2_Options, rest_Cycle_A, rest_Cycle_M, rest_Cycle_PHI, rest_Cycle_TAU, addCycles, add_Cycle_A, add_Cycle_M, add_Cycle_PHI, add_Cycle_TAU, shelterMatrix, forageMatrix, moveMatrix, seeds)
}

#' cpp_cycle_draw
#' @name cpp_cycle_draw
#' @param TIME A point in time (defined as a double) during the cycle to draw a value from.
#' @param A A double defining the amplitude of the cycle, calculated as the
#'   difference from M (i.e., half of the overall variation in the cycle from
#'   top to bottom).
#' @param M A double defining the cycle offset from 0 (Midline Statistic Of
#'   Rhythm, a rhythm-adjusted mean).
#' @param PHI A double defining the offset of the cycle (\eqn{\phi}; i.e.,
#'   acrophase). Must be kept proportional to \eqn{\tau} to avoid cycle drift.
#' @param TAU A double defining the cycle frequency (\eqn{\tau}; i.e., period),
#'   where \eqn{\tau} is the difference between peaks.
#' @return A double that is between M+A to M-A, draw from the defined cycle at TIME.
#' @details \eqn{\phi} must remain proportional to \eqn{\tau} if the cycle is to remained
#'   sync with period. If not proportional the cycle with drift.
#' @references Cornelissen, G. (2014). Cosinor-based rhythmometry. Theoretical
#'    Biology and Medical Modelling. 11(16)
#'    https://doi.org/10.1186/1742-4682-11-16
NULL

cpp_cycle_draw <- function(TIME, A, M, PHI, TAU) {
    .Call('_abmAnimalMovement_cpp_cycle_draw', PACKAGE = 'abmAnimalMovement', TIME, A, M, PHI, TAU)
}

#' cpp_get_values
#' @name cpp_get_values
#' @param MATRIX A numeric matrix that the value will be extracted from.
#' @param XLOCS A vector of x locations.
#' @param YLOCS A vector of y locations.
#' @return A vector of values equal to the length of XLOCS extracted from
#'   MATRIX.
#' @details A simple C++ function to extract a value from a Rcpp::NumericMatrix
#'   using two vectors describing location. Note that the counting begins for x
#'   and y begins at zero.
NULL

cpp_get_values <- function(MATRIX, XLOCS, YLOCS) {
    .Call('_abmAnimalMovement_cpp_get_values', PACKAGE = 'abmAnimalMovement', MATRIX, XLOCS, YLOCS)
}

#' Get maximum or minimum value
#' @name cpp_max/cpp_min
#' @param x A vector of doubles to the max/min found.
#' @return The maximum or minimum value in the vector.
NULL

cpp_max <- function(x) {
    .Call('_abmAnimalMovement_cpp_max', PACKAGE = 'abmAnimalMovement', x)
}

cpp_min <- function(x) {
    .Call('_abmAnimalMovement_cpp_min', PACKAGE = 'abmAnimalMovement', x)
}

#' @title cpp_sample_options
#' @name cpp_sample_options
#' @description The C++ sample function that takes a vector of weights and
#'   randomly returns an integer of the choice. Sampling solution based on:
#' [link](https://stackoverflow.com/questions/57599509/c-random-non-repeated-integers-with-weights).
#' With the of definition of pow2 coming from: [link](https://stackoverflow.com/questions/101439/the-most-efficient-way-to-implement-an-integer-based-power-function-powint-int).
#' A solution for the setting the random seed from: [link](https://www.r-bloggers.com/2018/09/using-rs-set-seed-to-set-seeds-for-use-in-c-c-including-rcpp/).
#'
#' @param W A vector of weights.
#' @param SEED The seed to be used for the sampling.
#' @details Requires a new seed for each run as a separate seed is set
#'   internally every time the function runs.
#' @return An integer corresponding to the chosen weight in the initially
#'   provided vector. __NOTE: indexing begins at 0 matching C++ convention__.
NULL

cpp_sample_options <- function(W, SEED) {
    .Call('_abmAnimalMovement_cpp_sample_options', PACKAGE = 'abmAnimalMovement', W, SEED)
}

#' @name cpp_vonmises
#' @title cpp_vonmises
#' @description A C++ conversion of the *rvm* function provided by the [CircStats package](https://cran.r-project.org/web/packages/CircStats/index.html).
#' @param N of values to draw.
#' @param MU The mean of the distribution (\eqn{\mu}).
#' @param KAPPA The concentration of the distribution (\eqn{\kappa}).
#' @return A vector drawn from a von Mises distribution equal in length to N.
#'
#' @references
#' S-plus original by Ulric Lund and R port by Claudio Agostinelli (2018). CircStats: Circular Statistics, from Topics in Circular Statistics (2001). R package version 0.2-6. https://CRAN.R-project.org/package=CircStats
#'
cpp_vonmises <- function(N, MU, KAPPA) {
    .Call('_abmAnimalMovement_cpp_vonmises', PACKAGE = 'abmAnimalMovement', N, MU, KAPPA)
}

#' Find max
#' @name find_max
#' @param vect a
#' @return index of max
NULL

find_max <- function(vect) {
    .Call('_abmAnimalMovement_find_max', PACKAGE = 'abmAnimalMovement', vect)
}

